version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
  m1:
    build:
      context: .
      dockerfile: Containerfile
      args:
        - SERVICE=m1
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - AMQP_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    restart: on-failure
    links:
      - rabbitmq
    volumes:
      - ./logs:/app/m1/logs
  m2:
    build:
      context: .
      dockerfile: Containerfile
      args:
        - SERVICE=m2
    environment:
      - AMQP_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    restart: on-failure
    links:
      - rabbitmq
    volumes:
      - ./logs:/app/m2/logs
